CREATE TABLE AGENCIA(
    id SERIAL,
    nombre VARCHAR(30), 
    pais VARCHAR(20),
    fecha_fundacion INTEGER,
    Autor_examen VARCHAR(15) DEFAULT "Sara Marco",
CONSTRAINT PK_AGENCIA PRIMARY KEY (id),
CONSTRAINT NN_AGENCIA_NOMBRE CHECK (nombre IS NOT NULL)
);



CREATE TABLE SATELITE(
    id SERIAL,
    nombre VARCHAR(30), 
    orbita VARCHAR(30),
    peso INTEGER,
    coste INTEGER,
    activo BOOLEAN DEFAULT true,
    agencia_id INTEGER,
    Autor_examen VARCHAR(30),
CONSTRAINT PK_SATELITE PRIMARY KEY (id),
CONSTRAINT FK_SATELITE_AGENCIA FOREIGN KEY (agencia_id) REFERENCES AGENCIA(id),
CONSTRAINT NN_SATELITE_AGENCIA CHECK (agencia_id IS NOT NULL),
CONSTRAINT NN_SATELITE_NOMBRE CHECK (nombre IS NOT NULL),
CONSTRAINT CK_SATELITE_PESO CHECK (peso >0), 
CONSTRAINT CK_SATELITE_coste CHECK (coste >0)
);


CREATE TABLE DETALLESATELITE (
    id SERIAL,
    velocidad INTEGER, 
    combustible INTEGER, --Si lo tomamos como cantidad no tipo
    vidaUtil INTEGER,
    temperatura_maxima INTEGER,
    satelite_id INTEGER,
    Autor_examen VARCHAR(30),
CONSTRAINT PK_DETALLE PRIMARY KEY (id),
CONSTRAINT CK_DETALLE_VELOCIDAD CHECK (velocidad > 0),
CONSTRAINT CK_DETALLE_COMBUSTIBLE CHECK (combustible > 0)
CONSTRAINT CK_DETALLE_VIDA CHECK (vidaUtil > 0),
CONSTRAINT FK_DETALLE_SATELITE FOREIGN KEY (satelite_id) REFERENCES SATELITE(id)
);


